version: '3'
services: 
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: matheusbizutti/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks: 
      - production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    networks: 
      - production-network
    ports:
      - "27017:27017"

  node1:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: matheusbizutti/node-sample-prj
    container_name: node1
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"
    environment:
      - URL_DATABASE_PROD=mongodb://mongodb:27017/sample-architecture
      - NODE_ENV=prod
      - DEBUG=*
    volumes:
      - .:/var/www

  node2:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: matheusbizutti/node-sample-prj
    container_name: node2
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"
    environment:
      - URL_DATABASE_PROD=mongodb://mongodb:27017/sample-architecture
      - NODE_ENV=prod
      - DEBUG=*
    volumes:
      - .:/var/www

  node3:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: matheusbizutti/node-sample-prj
    container_name: node3
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"
    environment:
      - URL_DATABASE_PROD=mongodb://mongodb:27017/sample-architecture
      - NODE_ENV=prod
      - DEBUG=*
    volumes:
      - .:/var/www
    
networks: 
  production-network:
    driver: bridge